### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [sujalgoel/discord-levelling-bot#3]
Add a function so bots dont levelup. My server bots are also gaining xp and are leveling up

**Comment by sujalgoel** [comment]
will look into it

**Comment by sujalgoel** [comment]
https://github.com/sujalgoel/discord-levelling-bot/blob/master/events/guild/message.js#L6
I guess your code has an issue when you tried merging it with mine! So, please check your code.

**Comment by Xx-Mohit-xX** [comment]
The thing is that the rank command is working fine, but leaderboard is showing bot xp too
